apiVersion: v1
kind: Service
metadata:
  name: {{Values.service.name}}
  namespace: {{Values.namespace}}
spec:
  selector:
    app: {{Values.appName}}
  type: {{Values.service.type}}
  ports:
    - protocol: TCP
      port: {{Values.service.port}}
      targetPort: {{Values.service.port}}
